version: '3.8'

services:
  pp-app-db:
    image: postgres
    restart: "no"
    shm_size: 128mb
    volumes:
      - pp-app-db:/var/lib/postgresql/data
    ports:
      - "1233:5432"
    env_file:
      - .env.local
    networks:
      - pp-app

  rmq:
    image: rabbitmq:3-management
    restart: "no"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - pp-app

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8081:8080
    networks:
      - pp-app

volumes:
  pp-app-db:
    name: pp-app-db

networks:
  pp-app:
    name: pp-app
    external: false
